<?php
require('fpdf/fpdf.php');
$texto = "Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.";
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',10);
$pdf->Image('img/LogoHorizontal.png',160,6,46,15);
$pdf->Image('img/SDUE.png',10,6,46,15);
$pdf->Cell(180,33,'SECRETARIA DE DESARROLLO URBANO Y ECOLOGIA',0, 1 ,'C');
$pdf->Ln(-8);
$pdf->Cell(0, 0,'OFICINA DE INFORMATICA',0,0, 'C');
$pdf->Ln(8);
$pdf->Ln(5);
$pdf->Cell(100, 0,'FOLIO: 691');
$pdf->Cell(0, 0,'FECHA: 10/31/18 01:02:55 PM');
$pdf->Ln(8);
$pdf->MultiCell(180,5,"ASUNTO: REACTIVACION DEL CONTRATO, DE LA MAN-31, LOTE 01, COLONIA PREVENIR, USUARIA C. MARISELA LUNA SALA");
$pdf->Ln(8);
$pdf->Cell(0,0,"USUARIO: JOSE ANTONIO PEREZ SANCHEZ");
$pdf->Ln(8);
$pdf->Cell(0,0,"DEPARTAMENTO: REGULARIZACION");
$pdf->Ln(8);
$pdf->Cell(0,0,"TECNICO: MYRNA ENRIQUEZ");
$pdf->Ln(8);
$pdf->Cell(0,0,"ETIQUETAS",0, 0, 'C');
$pdf->Ln(8);
$pdf->Cell(10,0,"");
$pdf->Cell(50,0,"E1: 54255");
$pdf->Cell(50,0,"E2: 65261616");
$pdf->Cell(50,0,"E3: 97487");
$pdf->Cell(20,0,"E4: 8743714");
$pdf->Ln(8);
$pdf->Cell(0,0,"DETALLES",0 , 0, "C");
$pdf->Ln(8);
$pdf->MultiCell(180,5,$texto,1 , 1);
$pdf->Ln(8);
$pdf->Cell(20,5,"CAUSA: ",0 , 0);
$pdf->Cell(14,5,"FALLA",0 , 0);
$pdf->Cell(10,5,"",1 , 0);
$pdf->Cell(30,5,"CAPACITACION",0 , 0);
$pdf->Cell(10,5,"",1 , 0);
$pdf->Cell(45,5,"NUEVO REQUERIMIENTO",0 , 0);
$pdf->Cell(10,5,"",1 , 0);
$pdf->Ln(10);
$pdf->Cell(100,5,"FECHA Y HORA DE ATENCION:________________________________________");
$pdf->Ln(12);
$pdf->Cell(100,0,"FIRMA DEL USUARIO:");
$pdf->Cell(100,0,"FIRMA DEL TECNICO:");
$pdf->Ln(8);
$pdf->Cell(100,0,"________________________");
$pdf->Cell(100,0,"________________________");
$pdf->Output();
?>